# Site settings
title: KC1RAO - Vincent Moeykens
email: kc1rao@moeykens.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kc1rao.radio" # replace with your website URL
github_username:  vmoeykens # replace with your GitHub username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
